// Notifications
export const FETCH_NOTIFICATIONS_START	= 'FETCH_NOTIFICATIONS_START';
export const FETCH_NOTIFICATIONS_DONE	= 'FETCH_NOTIFICATIONS_DONE';
export const FETCH_NOTIFICATIONS_ERROR	= 'FETCH_NOTIFICATIONS_ERROR';

// News
export const FETCH_NEWS_ITEMS_START		= 'FETCH_NEWS_ITEMS_START';
export const FETCH_NEWS_ITEMS_DONE		= 'FETCH_NEWS_ITEMS_DONE';
export const FETCH_NEWS_ITEMS_ERROR		= 'FETCH_NEWS_ITEMS_ERROR';
export const FETCH_NEWS_ITEM_START		= 'FETCH_NEWS_ITEM_START';
export const FETCH_NEWS_ITEM_DONE		= 'FETCH_NEWS_ITEM_DONE';
export const FETCH_NEWS_ITEM_ERROR		= 'FETCH_NEWS_ITEM_ERROR';
export const FETCH_NEWS_COMMENTS_START  = 'FETCH_NEWS_COMMENTS_START';
export const FETCH_NEWS_COMMENTS_DONE  	= 'FETCH_NEWS_COMMENTS_DONE';
export const FETCH_NEWS_COMMENTS_ERROR  = 'FETCH_NEWS_COMMENTS_ERROR';