// Notifications
export const FETCH_NOTIFICATIONS_START		= 'FETCH_NOTIFICATIONS_START';
export const FETCH_NOTIFICATIONS_DONE		= 'FETCH_NOTIFICATIONS_DONE';
export const FETCH_NOTIFICATIONS_ERROR		= 'FETCH_NOTIFICATIONS_ERROR';
export const FETCH_NOTIFICATIONS_N_START	= 'FETCH_NOTIFICATIONS_N_START';
export const FETCH_NOTIFICATIONS_N_DONE		= 'FETCH_NOTIFICATIONS_N_DONE';
export const FETCH_NOTIFICATIONS_N_ERROR	= 'FETCH_NOTIFICATIONS_N_ERROR';
export const VIEW_NOTIFICATIONS_START		= 'VIEW_NOTIFICATIONS_START';
export const VIEW_NOTIFICATIONS_DONE		= 'VIEW_NOTIFICATIONS_DONE';
export const VIEW_NOTIFICATIONS_ERROR		= 'VIEW_NOTIFICATIONS_ERROR';

// Posts
export const FETCH_POST_ITEMS_START			= 'FETCH_POST_ITEMS_START';
export const FETCH_POST_ITEMS_DONE			= 'FETCH_POST_ITEMS_DONE';
export const FETCH_POST_ITEMS_ERROR			= 'FETCH_POST_ITEMS_ERROR';
export const FETCH_POST_ITEM_START			= 'FETCH_POST_ITEM_START';
export const FETCH_POST_ITEM_DONE			= 'FETCH_POST_ITEM_DONE';
export const FETCH_POST_ITEM_ERROR			= 'FETCH_POST_ITEM_ERROR';
export const FETCH_POST_COMMENTS_START 		= 'FETCH_POST_COMMENTS_START';
export const FETCH_POST_COMMENTS_DONE  		= 'FETCH_POST_COMMENTS_DONE';
export const FETCH_POST_COMMENTS_ERROR  	= 'FETCH_POST_COMMENTS_ERROR';
export const TOGGLE_LIKE_START  			= 'TOGGLE_LIKE_START';
export const TOGGLE_LIKE_DONE  				= 'TOGGLE_LIKE_DONE';
export const TOGGLE_LIKE_ERROR  			= 'TOGGLE_LIKE_ERROR';
export const ADD_COMMENT_ITEM_START			= 'ADD_COMMENT_ITEM_START';
export const ADD_COMMENT_ITEM_DONE			= 'ADD_COMMENT_ITEM_DONE';
export const ADD_COMMENT_ITEM_ERROR			= 'ADD_COMMENT_ITEM_ERROR';
export const DELETE_POST_ITEM_START			= 'DELETE_POST_ITEM_START';
export const DELETE_POST_ITEM_DONE			= 'DELETE_POST_ITEM_DONE';
export const DELETE_POST_ITEM_ERROR			= 'DELETE_POST_ITEM_ERROR';
export const DELETE_COMMENT_ITEM_START		= 'DELETE_COMMENT_ITEM_START';
export const DELETE_COMMENT_ITEM_DONE		= 'DELETE_COMMENT_ITEM_DONE';
export const DELETE_COMMENT_ITEM_ERROR		= 'DELETE_COMMENT_ITEM_ERROR';